### PR TITLE
Revised dark mode theme switcher to maintain theme throughout various…

### PR DESCRIPTION
**Pull request by mbussert**
… pages.

### CODE REVIEW

**Comment by bacloud14** [comment]
Hello @mbussert 
Thank you for your contribution. Excuse me but I am not sure about the changes ? All are code reformatting ?

**Comment by bacloud14** [comment]
Thanks Mike for your contribution. I see the logic and yes, we need this indeed to maintain the state between pages.
sadly, I cannot see what it broke because I does not work now.
I will recheck this later or tomorrow
thanks

**Comment by bacloud14** [comment]
it was just the class "dark" in body instead of html node as expected from "chota.css" library,

thanks a lot for your contribution !!

**Comment by mbussert** [comment]
Absolutely, you're welcome!

**Pull request merged**
